[build]
  functions = "api/"
  publish = "build/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 307

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#custom"
  command = "react-scripts start"
  targetPort = 8080
  port = 3000
  publish = "public"
  autoLaunch = false
