[build]
  functions = "api/"
  publish = "build/"
  command = "npm run lint && npm run test.all && npm run coverage.upload && npm run build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 307

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#custom"
  command = "vue-cli-service serve"
  targetPort = 8080
  port = 3000
  publish = "public"
  autoLaunch = false
